=== al3xHub/Introducing-in-XML/ejercicio4T4.dtd
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, autores, editorial, descripcion, copy*)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT copy (#PCDATA)>

<!ENTITY copyright SYSTEM "Alejandro 2023">
<!ENTITY ciudad SYSTEM "Sevilla">

=== al3xHub/Introducing-in-XML/ejercicio4T4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE libros SYSTEM "./ejercicio4T4.dtd" >

<libros>
    <libro>
        <titulo>El Quijote</titulo>
        <autores>
            <autor>Miguel de Cervantes</autor>
        </autores>
        <editorial>Anaya</editorial>
        <descripcion>Burla de las novelas de caballeria</descripcion>
    </libro>

    <libro>
    <titulo>Buenos Presagios</titulo>
        <autores>
            <autor>Neil Gaiman</autor>
            <autor>Tery Pratchett</autor>
        </autores>
        <editorial>McGraw Hill</editorial>
        <descripcion>Comedia de tono ir√≥nico sobre el anticristo</descripcion>
        <copy>&copyright;&ciudad;</copy>
    </libro>

</libros>
